INSERT INTO ORD_SHOP (SHOP_ID,OWNER_USER_ID) VALUES (1,1000);

INSERT INTO ORD_PRODUCT (PRODUCT_ID,SHOP_ID,PRODUCT_NAME,PRICE) VALUES (1,1,'IPhone6S',5288);
INSERT INTO ORD_PRODUCT (PRODUCT_ID,SHOP_ID,PRODUCT_NAME,PRICE) VALUES (2,1,'MAC Pro',10288);
INSERT INTO ORD_PRODUCT (PRODUCT_ID,SHOP_ID,PRODUCT_NAME,PRICE) VALUES (3,1,'IWatch',2288);