INSERT INTO RED_RED_PACKET_ACCOUNT (RED_PACKET_ACCOUNT_ID,BALANCE_AMOUNT,USER_ID) VALUES (1,950,1000);
INSERT INTO RED_RED_PACKET_ACCOUNT (RED_PACKET_ACCOUNT_ID,BALANCE_AMOUNT,USER_ID) VALUES (2,500,2000);
